spring:
  application:
    name: MS-ORDER
  data:
    mongodb:
      user: desafio
      password: engenharia
      database: desafio_engenharia
    rabbitmq:
      host: localhost
      port: 5672
server:
  port: 8084
rabbitmq:
  queues:
    order-created-payment-queue: "order_created_payment_queue"
    order-received-payment-queue: "order_received_payment_queue"
  routingKey: "ms-order_created"
grpc:
  server:
    port: 4005
  clients:
    customer:
      address: localhost
      port: 4004
    order:
      address: localhost
      port: 4005
    payment:
      address: localhost
      port: 4006
    product:
      address: localhost
      port: 4007