spring:
  application:
    name: MS-BACKEND-FOR-FRONTEND
  data:
    mongodb:
      user: ${DB_USER}
      password: ${DB_PASS}
      uri: ${DB_CONN_STRING}
server:
  port: 8081
grpc:
  clients:
    customer:
      address: "http://localhost/"
      port: 4004
    order:
      address: "http://localhost/"
      port: 4005
    payment:
      address: "http://localhost/"
      port: 4006
    product:
      address: "http://localhost/"
      port: 4007