spring:
  application:
    name: MS-BACKEND-FOR-FRONTEND
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081
grpc:
  server:
    port: 4003
  clients:
    customer:
      address: localhost
      port: 4004
    order:
      address: localhost
      port: 4005
    payment:
      address: ms-payment
      port: 4006
    product:
      address: ms-product
      port: 4007
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'info,health,metrics,prometheus'
  server:
    port: 9090
    address: prometheus
    servlet:
      context-path: /actuator