spring:
  application:
    name: MS-BACKEND-FOR-FRONTEND
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081
grpc:
  server:
    port: 9090
  clients:
    customer:
      address: ms-customer
      port: 4004
    order:
      address: localhost
      port: 4005
    payment:
      address: ms-payment
      port: 4006
    product:
      address: ms-product
      port: 4007