apiVersion: v1
kind: Service
metadata:
  name: ms-customer
  labels:
    app: ms-customer
    tier: backend
spec:
  selector:
    app: ms-customer
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8082
    - name: grpc
      port: 4004
      protocol: TCP
      targetPort: 4004
  type: NodePort
