apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    tier: backend
spec:
  selector:
    app: rabbitmq
  ports:
    - name: http
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: management
      port: 15672
      protocol: TCP
      targetPort: 15672
  clusterIP: 10.97.0.21
  type: NodePort
