global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['ms-bff:8080', 'ms-customer:8080', 'ms-order:8080', 'ms-payment:8080', 'ms-product:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']