global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['ms-customer:8080', 'ms-order:8080', 'ms-payment:8080', 'ms-product']
