apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
            - name: cluster.name
              value: elasticsearch
          volumeMounts:
            - name: esdata
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: esdata
          persistentVolumeClaim:
            claimName: elasticsearch-data