spring:
  application:
    name: MS-PAYMENT
  data:
    mongodb:
      user: ${MONGODB_USER}
      password: ${MONGODB_PASS}
      database: desafio_engenharia
      host: ${MONGODB_HOST}
  rabbitmq:
    host: rabbitmq
    port: 5672
server:
  port: 8083
rabbitmq:
  queues:
    order-created-payment-queue: "order_created_payment_queue"
    order-received-payment-queue: "order_received_payment_queue"
  routingKey: "ms-payment_received"
grpc:
  server:
    port: 4006
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'info,health,metrics,prometheus'
  server:
    port: 9090
    address: prometheus
    servlet:
      context-path: /actuator