spring:
  application:
    name: MS-PAYMENT
  data:
    mongodb:
      user: ${MONGODB_USER:desafio}
      password: ${MONGODB_PASS:engenharia}
      database: desafio_engenharia
      host: ${MONGODB_HOST:10.0.0.107}
  rabbitmq:
    host: rabbitmq
    port: 5672
server:
  port: 8083
rabbitmq:
  queues:
    order-created-payment-queue: "order_created_payment_queue"
    order-received-payment-queue: "order_received_payment_queue"
  routingKey: "ms-payment_received"
grpc:
  server:
    port: 4006