spring:
  application:
    name: MS-PAYMENT
  data:
    mongodb:
      user: desafio
      password: engenharia
      database: desafio_engenharia
    rabbitmq:
      host: localhost
      port: 5672
server:
  port: 8083
rabbitmq:
  queues:
    order-created-payment-queue: "order_created_payment_queue"
    order-received-payment-queue: "order_received_payment_queue"
  routingKey: "ms-payment_received"
grpc:
  server:
    port: 4006