apiVersion: v1
kind: Service
metadata:
  name: ms-order
  labels:
    app: ms-order
    tier: backend
spec:
  selector:
    app: ms-order
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: grpc
      port: 4005
      protocol: TCP
      targetPort: 4005
  clusterIP: 10.97.0.11
  type: NodePort
