spring:
  application:
    name: MS-PRODUCT
  data:
    mongodb:
      user: ${MONGODB_USER}
      password: ${MONGODB_PASS}
      database: desafio_engenharia
      host: ${MONGODB_HOST}
server:
  port: 8080
grpc:
  server:
    port: 4007
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'info,health,metrics,prometheus'
  server:
    port: 9090
    address: prometheus
    servlet:
      context-path: /actuator