apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-product
  labels:
    app: ms-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-product
  template:
    metadata:
      labels:
        app: ms-product
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: ms-product
          image: nihbertolo97/desafio-engenharia-sofware:btg-ms-product
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 4007
              name: grpc
          env:
            - name: MONGODB_USER
              value: desafio
            - name: MONGODB_PASS
              value: engenharia
            - name: MONGODB_HOST
              value: 10.0.0.107
        - name: sidecar-redis
          image: redis:latest
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password