apiVersion: v1
kind: Service
metadata:
  name: ms-product
  labels:
    app: ms-product
    tier: backend
spec:
  selector:
    app: ms-product
  ports:
    - name: http
      port: 8085
      protocol: TCP
      targetPort: 8085
    - name: grpc
      port: 4007
      protocol: TCP
      targetPort: 4007
  clusterIP: 10.97.0.13
  type: NodePort
