sprincg:
  application:
    name: MS-CUSTOMER
  data:
    mongodb:
      user: desafio
      password: engenharia
      database: desafio_engenharia
server:
  port: 8085
grpc:
  server:
    port: 4004
